print ('Crée ton personnage')
nom = input('Nom du perso: ')
age = input ('age du perso: ')
force = input ('force du perso: ')
faiblesse =input('faiblesse du perso: ')
print('ton perso s\'appelle ',nom)
print('il a ',age,' ans')
print (force, ' en force')
print( faiblesse, ' est son point faible ')
print (nom,' dit Merci de m\'avoir créé')